nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Chelsea Sawyer, Yuk Kei Wan
  description: A pipeline to demultiplex, QC and map Nanopore data
  force: false
  is_nfcore: true
  name: nanoseq
  org: nf-core
  outdir: .
  version: 3.1.0
